#!/bin/bash 

for i in $(seq 0 50 ) ; do 
	for j in $(seq 0 50); 
		do echo "testforblock $i 4 $j minecraft:grass"> ~/.minecraft/server/mcs_pipe ; 
	done; 
done;
sleep 1.0 # we gotta wait for the server to output
tail -n $((51*51)) ~/.minecraft/server/mcs_output > /tmp/mcs_data_tmp
cat /tmp/mcs_data_tmp | awk '
/Stone/ {printf "#"} 
/Torch/ {printf "L"} 
/Wood/ {printf "s"} 
/Wool/ {printf "0"} 
/Bedrock/ {printf " "} 
/air/ {printf "."} 
NR%51==0 {printf"\n"} ' | head -n 50
